### ISSUE TITLE
One issue about Tab autocompletion

### ISSUE THREAD

**Issue by bj600800** [MooersLab/pymolsnips#22]
First of all, thanks for your efforts! Application software in the field of biology requires indispensable automated auxiliary tools, which could greatly reduce learning costs and increase work efficiency.

After I install the PYMOLSNIPS (followed by the instructions from site: https://mooerslab.github.io/pymolsnips/#SublimeText3), part of the tab triggers is valid (ao; coordinate; sc222; stack) but the others are not.

if it's convenient for you, could you please give me some suggestions to address the problem?

Thanks for your time and your work again!

**Comment by MooersLab** [comment]
Thank you for the compliments and *especially* thank you for pointing out that some tab triggers were not working.
I found that those snippets were missing. This was the only library that was not properly updated with the full set of snippets.
The full set of snippets for Sublime Text is now on GitHub. Please download the library again and copy the snippets:

```bash
cp -a ./pymolsnips-master/st3pymolsnips/* ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/snippets/Pymol/.
```

When satisfied that all is well, please close this issue.

**Comment by bj600800** [comment]
GOT IT. Thanks for your reply.

**Comment by MooersLab** [comment]
I closed this issue after waiting for a month.
