### ISSUE TITLE
It doesn't work for vscode.

### ISSUE THREAD

**Issue by 9527567** [MooersLab/pymolsnips#24]
It's a really amazing project.I want to know if there is a syntax error in vscpymolsnips? I'm not an expert on JSON. The online JSON parsing tool tells me this information.Have a nice day.
![1622962225(1)](https://user-images.githubusercontent.com/50236967/120915499-96c92e00-c6d6-11eb-89d8-57f5b5feae92.png)

**Comment by MooersLab** [comment]
Dear 9527567,

Thank you very much for bringing this issue to my attention. 
I broke it by accident. It is now fixed and works in VSC as advertised.

Best regards,

Blaine
