### ISSUE TITLE
CudaText snippets published

### ISSUE THREAD

**Issue by Alexey-T** [MooersLab/pymolsnips#3]
CudaText snippets are now in Plugins/ Addon Manager/ Install list.

What i've changed in your files:

- replaced `$0` to `${0}` so tabstop zero now works
- replaced `=PML_` to `=PyMOL` (lexer name is PyMOL)

**Comment by Alexey-T** [comment]
Zip is at
https://sourceforge.net/projects/cudatext/files/addons/snippets/

**Comment by MooersLab** [comment]
Closing this issue.
